### ISSUE TITLE
头部搜索不能按下

### ISSUE THREAD

**Issue by pursonchen** [zzmhot/vue-admin#2]
在组件中headerSetion 修改index.vue 为
 <div class="header-section">
    <el-row :gutter="24">
    <el-col :span="16">
    <div class="search" >
      <search @search="submit_search"></search>
    </div>
    </el-col>
    <el-col :span="8">
    <menu-right></menu-right>
    </el-col>
    </el-row>
  </div>

**Comment by zzmhot** [comment]
已修改，z-index原因造成的

**Comment by KeKe-Li** [comment]
我运行npm install后运行npm run dev直接报错了

`

> vue-element-admin@1.0.0 dev /home/keke/Documents/vue-admin
> node build/dev-server.js

> Starting dev server...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at EventEmitter.listen (/home/keke/Documents/vue-admin/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/keke/Documents/vue-admin/build/dev-server.js:98:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

npm ERR! Linux 3.10.0-327.36.2.el7.x86_64
npm ERR! argv "/home/keke/soft/node/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-element-admin@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-element-admin@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-element-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-element-admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-element-admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/keke/Documents/vue-admin/npm-debug.log

`

**Comment by zzmhot** [comment]
请重新安装依赖

**Comment by pursonchen** [comment]
端口冲突，修改端口试试

**Comment by KeKe-Li** [comment]
这个好像是国内镜像问题，我用Vpn就好了！还有个问题单元测试可以加下，这样更好的展示！谢谢
